# **Learning Numpy** 
NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing. 
It provides support for working with large, multi-dimensional arrays and matrices, along with a wide variety of 
high-level mathematical functions to operate on these arrays. NumPy is highly optimized for performance and serves 
as the foundation for many other scientific and machine learning libraries such as Pandas, SciPy, TensorFlow, and 
scikit-learn. By using NumPy, we can perform vectorized operations, handle complex computations efficiently, and 
manipulate data in ways that are far more efficient than using Python lists.


## Importing Numpy

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3,4,5]

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [7]:
type(arr)

numpy.ndarray

## **Creating Multidimensional Array**

In [8]:
my_list_1 = [1,2,3,4,5]
my_list_2 = [1,2,3,4,5]
my_list_3 = [1,2,3,4,5]

In [10]:
mul_arry = np.array([my_list_1,my_list_2,my_list_3])

In [11]:
mul_arry

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [13]:
mul_arry.shape

(3, 5)

In [15]:
mul_arry.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 1],
       [2, 3, 4],
       [5, 1, 2],
       [3, 4, 5]])

## **Indexing**

In [16]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [17]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[3]

np.int64(4)

In [19]:
arr[0]

np.int64(1)

In [20]:
mul_arry

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [22]:
mul_arry[1:,3:]

array([[4, 5],
       [4, 5]])

In [26]:
arry_2 = np.array([[1,2,3,4,5],
                  [2,3,4,5,6],
                  [4,5,6,7,8]])

In [27]:
arry_2[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [29]:
arry_2[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [31]:
arry_2[1:,3:]

array([[5, 6],
       [7, 8]])

In [33]:
arry_2[1:,1:4]

array([[3, 4, 5],
       [5, 6, 7]])

## **Arange**

In [35]:
ran = np.arange(0,10)

In [36]:
ran

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
ran_2 = np.arange(0,10,2)

In [39]:
ran_2

array([0, 2, 4, 6, 8])

In [40]:
lin = np.linspace(1,100,50)

In [41]:
lin

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

## **Copy**
**Copy() function and broadcasting.**

In [42]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr[3:]=100

In [45]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [49]:
arr1 = arr.copy()

In [50]:
arr1

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [52]:
arr1<2

array([ True, False, False, False, False, False, False, False, False])

In [54]:
arr2 = np.arange(0,10).reshape(5,2)

In [55]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
arr3 = np.arange(0,10).reshape(2,5)

In [57]:
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
arr4 = np.arange(0,10).reshape(2,5)

In [60]:
arr4*arr3

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

## **Random Disterbution**

In [61]:
rand = np.random.rand(2,4)

In [62]:
rand

array([[0.26601192, 0.40856055, 0.30758022, 0.91597245],
       [0.83159673, 0.10028653, 0.4882004 , 0.93708388]])